version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    image: frontend:local
    container_name: frontend
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL","curl -fsS http://localhost:8080/healthz || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  pokemon-manager:
    build:
      context: ./pokemon_manager
    image: pokemon-manager:local
    container_name: pokemon-manager
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD-SHELL","curl -fsS http://localhost:8081/healthz || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    depends_on:
      frontend:
        condition: service_healthy

  scheduler:
    build:
      context: ./scheduler
    image: scheduler:local
    container_name: scheduler
    ports:
      - "8082:8082"
    healthcheck:
      test: ["CMD-SHELL","curl -fsS http://localhost:8082/healthz || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    depends_on:
      pokemon-manager:
        condition: service_healthy

  pokemon-fetcher:
    build:
      context: ./pokemon_fetcher
    image: pokemon-fetcher:local
    container_name: pokemon-fetcher
    ports:
      - "8083:8083"
    healthcheck:
      test: ["CMD-SHELL","curl -fsS http://localhost:8083/healthz || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    depends_on:
      scheduler:
        condition: service_healthy

  battle-manager:
    build:
      context: ./battle_manager
    image: battle-manager:local
    container_name: battle-manager
    ports:
      - "8084:8084"
    healthcheck:
      test: ["CMD-SHELL","curl -fsS http://localhost:8084/healthz || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    depends_on:
      pokemon-manager:
        condition: service_healthy
      trainer-manager:
        condition: service_healthy

  trainer-manager:
    build:
      context: ./trainer_manager
    image: trainer-manager:local
    container_name: trainer-manager
    ports:
      - "8085:8085"
    healthcheck:
      test: ["CMD-SHELL","curl -fsS http://localhost:8085/healthz || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped
