apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: app
data:
  TRAINER_URL: http://trainer-manager.app.svc.cluster.local:8085
  POKEMON_URL: http://pokemon-manager.app.svc.cluster.local:8081
  BATTLE_URL: http://battle-manager.app.svc.cluster.local:8084
  SCHEDULER_URL: http://scheduler.app.svc.cluster.local:8082
  FETCHER_URL: http://pokemon-fetcher.app.svc.cluster.local:8083
