apiVersion: apps/v1
kind: Deployment
metadata:
  name: trainer-manager
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trainer-manager
  template:
    metadata:
      labels:
        app: trainer-manager
    spec:
      serviceAccountName: app-sa
      containers:
      - name: trainer-manager
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        # critical required for HPA and Fargate sizing
        image: s1natex/pokemon_game:trainer-manager-initial # ci updates image tag here
        ports:
        - containerPort: 8085
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8085
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8085
          initialDelaySeconds: 20
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: trainer-manager
  namespace: app
spec:
  selector:
    app: trainer-manager
  ports:
  - port: 8085
    targetPort: 8085
    name: http
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: trainer-manager
  namespace: app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: trainer-manager
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
