apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pokemon-game-app
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: terraform
spec:
  project: default
  source:
    repoURL: https://github.com/s1natex/Pokemon_Game
    targetRevision: main
    path: k8s/app
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
